config/routes.rb
Rails.application.routes.draw do

root 'users#new'
resources :users, except: [:destroy]

end

app/models/user.rb
class User < ActiveRecord::Base
  validates_format_of :email, :with => /^(|(([A-Za-z0-9]+_+)|([A-Za-z0-9]+\-+)|([A-Za-z0-9]+\.+)|([A-Za-z0-9]+\++))*[A-Za-z0-9]+@((\w+\-+)|(\w+\.))*\w{1,63}\.[a-zA-Z]{2,6})$/i, :multiline => true
  validates_format_of :social_security_number, :with => /^(?!219099999|078051120)(?!666|000|9\d{2})\d{3}(?!00)\d{2}(?!0{4})\d{4}$/i, :multiline => true
  after_save :write_json

  def write_json
    users_json = []
    User.all.each do |user|
      user_json = {
        "firstname" => user.first_name,
        "lastname" => user.last_name,
        "email" => user.email,
        "social_security_number" => user.social_security_number
      }
      users_json << user_json
    end
    File.open("public/user.json", "w") do |f|
      f.write(users_json.to_json)
    end
  end  

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end  

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to "/user.json"
    else
      render :new
    end
  end

  def index
    @users = User.all.order('created_at DESC')
  end

  def show
    @user = User.find(params[:id])
    if params[:search]
      @users = User.search(params[:search]).order("created_at DESC")
    end
  end


  private 

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :social_security_number)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>InterviewProblem</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/shared/_error_messages.html.erb
<% if target.errors.any? %>
<div id="errorExplanation">
  <h2><%= pluralize(target.errors.count, "error") %> prohibited this record from being saved:</h2>
  <ul>
  <% target.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
  <% end %>
  </ul>
</div>
<% end %>

app/views/users/index.html.erb
    <tr>
    <% @users.each do |result| %>      
      <td>User ID:<%= result.id %></td><br/>
      <td>First Name:<%= result.first_name %></td><br/>
      <td>Last Name:<%= result.last_name %></td><br/>
      <td>Email:<%= result.email %></td><br/>
      <%= link_to 'Show this user only', user_path(result) %>
    </tr>

    <br/>
    <br/>

    <% end %>

    <%= link_to 'Back to home', root_path %>

app/views/users/new.html.erb
<script type="text/javascript">
function f(o){
  o.value=o.value.replace(/(-)/g,"");
}
</script>

<%= form_for User.new do |f| %>

<%= render "shared/error_messages", :target => @user %>

First name
  <%= f.text_field :first_name, :required => true %>
<br/>
<br/>
Last name
  <%= f.text_field :last_name, :required => true %>
<br/>
<br/>
Email
  <%= f.text_field :email, :required => true %>
<br/>
<br/>
Social Security Number

  <input type="text"
         onmouseout="f(this)"
         onkeyup="f(this)"
         onblur="f(this)"
         onclick="f(this)"          
  <%= f.text_field :social_security_number, :size=>9, :required => true %>
  </>
<br/>
<br/>
<%= f.submit "Register", class: 'btn btn-primary' %>
<br/>
<br/>
<%= link_to 'See list of all users', users_path %>


<% end %>

app/views/users/show.html.erb
User ID:<%= @user.id %><br/>
First Name:<%= @user.first_name %><br/>
Last Name:<%= @user.last_name %><br/>
Email:<%= @user.email %><br/>

<br/>
<br/>

<%= link_to 'Back to home', root_path %>